echo "Updating package list"
opkg update
echo ""
echo "--"
echo "Installing SFTP server"
opkg install openssh-sftp-server
echo ""
echo "--"
echo "Installing php5 and required modules"
opkg install php5 php5-cgi php5-mod-gd php5-mod-json php5-mod-pdo php5-mod-pdo-sqlite php5-mod-sqlite
echo ""
echo "--"
echo "Installing sqlite3 server"
opkg install libsqlite3 sqlite3-cli
echo ""
echo "--"
echo "Installing timezone files"
opkg install zoneinfo-core
echo ""
echo "--"
echo "After installation, edit /etc/php.ini and enable the following extensions:"
echo "extension=gd.so"
echo "extension=json.so"
echo "extension=pdo_sqlite.so"
echo "extension=sqlite3.so"
echo "and set timezone:"
echo "date.timezone = GMT+8"
echo ""
echo "--"
echo "Copy the following files to the root of the sd card (/mnt/sda1)"
echo "upgrade.sh"
echo "packages.sh"
echo "create.sql"
echo ""
echo "--"
echo "After installation, edit /etc/config/uhttpd and change the following lines"
echo 'list interpreter ".php=/usr/bin/php-cgi"'
echo "option max_requests 10"
echo 'Then restart the web server with "/etc/init.d/uhttpd restart"'
echo ""
echo "--"
echo "Last step create the database on the root of the sd card (/mnt/sda1) with"
echo "cd /mnt/sda1"
echo "sqlite3 s.db < create.sql"
echo ""
echo "--"
echo "Now you can install the spMonitor on the Arduino Yun"
